kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-server-config
  namespace: default
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log debug ;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
        debug_connection 172.0.0.1;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   500;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        server {
             #listen       8865;
             listen       9965 default_server ssl;
             listen       [::]:9965 default_server ssl;
             server_name  _;

             ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
             ssl_certificate_key /etc/ssl/certs/nginx-selfsigned.key;
             ssl_dhparam /etc/ssl/certs/dhparam.pem;

            location / {
                proxy_pass                 http://127.0.0.1:8080;
                proxy_set_header           X-Real-IP $remote_addr;
                proxy_set_header           Host $host;
                proxy_set_header           Access-Control-Allow-Origin *;

                proxy_pass_header          Server;

                # enable Web Sockets
                proxy_http_version         1.1;
                proxy_set_header           Upgrade 'websocket';
                proxy_set_header           Connection 'Upgrade';

                proxy_connect_timeout       300;
                proxy_send_timeout          300;
                proxy_read_timeout          300;
                send_timeout                300;

                proxy_ignore_client_abort   on;
                proxy_redirect              off;
            }

            error_page 404 /404.html;
                location = /40x.html {
            }

            error_page 500 502 503 504 /50x.html;
                location = /50x.html {
            }
        }
    }
